# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "ehci_pci" "ahci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0c033bc5-7f6d-47e1-aa9d-de38af422d07";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/00721472-283b-4afd-b7b9-fd742d54a0cc"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
